### ISSUE TITLE
Speed up the config diff

### ISSUE THREAD

**Issue by jrs65** [chime-experiment/coco#161]
The config diff takes forever (~1s per config being checked). However there's usually only a few variations at desync. Hashing a serialised config is super quick (~15ms), so we should probably build up a cache of hashes to `DeepDiff`s as we go through it. You'd simply use a `dict` which maps a tuple of `(hash(state_value), hash(host_value)) -> DeepDiff`

Doing this I imagine we'd be able to get the desync check down from 3m30s to more like 30s, which is way better.

**Comment by nritsche** [comment]
The idea is great, but I don't see a way to do this with coco's design. That's because the config diff is done like this:
There's an endpoint config for `/config_md5sum`. It tells coco to compare the returned hash with the hash of coco's internal state.
For nodes failing the test, there's another endpoint config, calling `/config`. 

Both forwarding the previous result or telling the config that knows `/config` to call `/config_md5sum` again would need a lot of changes.

How about we turn off the calls to `/config` and restart nodes already if the md5sum mismatches?

**Comment by jrs65** [comment]
I think my proposal wasn't clear. You don't need to connect the too, just use one of Python's standard lib hash functions within the `/config` endpoint to hash the string sent by each kotekan node and use that as the key in a dict to store the `DeepDiff` result. The standard lib hash functions are way faster than a DeepDiff call.

**Comment by nritsche** [comment]
Hashing a dict is not trivial, so I refactored the hashing function from `coco.state`.
