### ISSUE TITLE
Export prometheus metrics for endpoint calls

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#19]
depends on #11 
For every endpoint call export counters:

- `coco_<endpoint name>_total` for incoming messages
  - needs to be done in the sanic endpoint in `master.py`
- `coco_<endpoint name>_success` labels: [host] for forwarded messages
  - Could be done in `request_forwarder._request`
- `coco_<endpoint name>_failure` labels: [host, err] for forwarded messages showing the HTTP error code
  - Could be done in `request_forwarder._request`

**Comment by tristpinsm** [comment]
There is a PR (https://github.com/chime-experiment/coco/pull/66) in for this. During development, we decided we would like to track the number of requests dropped when the queue is full, rather than just the total number of requests received. Since limiting the queue hasn't been implemented yet, the code currently tracks all requests. We will need to change this when #42 is addressed.

**Comment by nritsche** [comment]
Closed by #114
