### ISSUE TITLE
Add endpoint: /toggle-rfi-zeroing

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#55]
- takes a boolean and forwards to `rfi_masking/toggle` on all GPU nodes
- saves bool in state (used by `/status`)
 rename this (it doesn't just toggle)

**Comment by nritsche** [comment]
Removed from kotekan in version `2019.07`

**Comment by andrerenard** [comment]
We are going to add this back into kotekan once we fix the issues with the RFI system.  So you might still want to plan to have this long term.   I don't think the status part is needed, but the forwarding should exist.  Although since it's already updatable config, it might get obsoleted by the auto registration later.

**Comment by nritsche** [comment]
Altright, thanks @andrerenard. This is just configuration changes by now. Please reopen when needed.
