### ISSUE TITLE
Scheduler: add option to only run a scheduled endpoint call if some state matches a value

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#82]
Many watchdog tasks (endpoints called by scheduler) only make sense when the cluster is started. So we need an option that checks a state value before calling a scheduled call.

Also needed by #81 

Depends on #12

**Comment by tristpinsm** [comment]
Because the state is held in memory by the worker process, the scheduler doesn't have access to any changes made to the state by endpoint calls. A possible solution would be to move the scheduler to the worker process. This shouldn't be too hard. Since it is already async, it could just run in parallel to the main loop.

**Comment by tristpinsm** [comment]
I've done this now and it is working, but we may want to revisit this in case it causes performances issues.

**Comment by nritsche** [comment]
Closed by #88
